version: "3.0"
services:
  # Web server, running in development mode
  api:
    command: debug
    environment:
      NODE_ENV: development
    build: ./
    networks:
      - backend
    ports:
      - "8081:3000"
      - "9229:9229"
    volumes:
      - ./:/usr/src/app

networks:
  backend: ~
