import { ApiResponse } from "@app/core/responses"

/**
 * Base class for errors that have a dedicated API response.
 * Any uncaught error that does not extend from `ApiError` result in an `HTTP 500 - Internal Server Error`.
 *
 * The shape and status of the HTTP response is described by the `ApiResponse` generated by `handle`.
 */
export abstract class ApiError extends Error {
  /**
   * @param message Optional message describing the error for debugging purposes.
   */
  protected constructor(message?: string) {
    super(message)
    this.name = this.constructor.name
  }

  /**
   * Handle the error, generating a response to be sent to the API client.
   */
  abstract handle(): ApiResponse
}
