/**
 * A character sequence generated by the server after an user has successfully
 * authenticated using its credentials.
 * This user can then authenticate its requests using this token in place of its credentials.
 *
 * Access tokens automatically expire a given duration after being generated;
 * authentication may then be renewed by generating a new token.
 */
export type AccessToken = {
  /**
   * Generated character sequence that should be used to authenticate user requests.
   */
  token: string
  /**
   * Duration in seconds from the moment this token has been generated
   * during which it is considered valid.
   * This should be a strictly positive integer.
   */
  expiresIn: number
}
